apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - database.yaml

patches:
  - path: frontend-hpa.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: frontend
  - path: backend-hpa.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: backend
