frontend:
  image: frontend
  tag: 'latest'
  autoscaling:
    averageUtilization: 90
backend:
  image: backend
  tag: 'latest'
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
  
