frontend:
  image: frontend
  tag: latest
  autoscaling:
    averageUtilization: 50

backend:
  image: backend
  tag: latest
  autoscaling:
    averageUtilization: 50

database:
  enabled: false
  uri: 10.10.10.10
  username: external_postgres
  password: external_postgres
